
# MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cuteslkdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

jwt.secret=xd1x5rI9sQmJc8LmNz2BqRfUoSeKpwYtZgHnA4dFv4kX1c3P
jwt.expiration-ms=86400000

